### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by guanchenY** [jovans2/MXFaaS_Artifact#4]
When I execute the command "python3 cnn_serving.py", I get the following error. Can you please tell me how to fix it?

Traceback (most recent call last):
  File "cnn_serving.py", line 53, in <module>
    lambda_handler()
  File "cnn_serving.py", line 24, in lambda_handler
    download_stream = blob_client.download_blob()
  File "/usr/local/lib/python3.8/dist-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_blob_client.py", line 914, in download_blob
    return StorageStreamDownloader(**options)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_download.py", line 366, in __init__
    self._response = self._initial_request()
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_download.py", line 466, in _initial_request
    process_storage_error(error)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: The specified account is disabled.
RequestId:32d7912c-601e-0011-0862-b2b16b000000
Time:2023-07-09T12:39:32.0469709Z
ErrorCode:AccountIsDisabled
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AccountIsDisabled</Code><Message>The specified account is disabled.
RequestId:32d7912c-601e-0011-0862-b2b16b000000
Time:2023-07-09T12:39:32.0469709Z</Message></Error>

**Comment by jovans2** [comment]
Hello, thanks for your comment! The blob storage account we used for the Artifact Evaluation expired. You need to set up your Azure Blob Storage account and create a container with the data there. Then, you just need to change the _*connection_string*_ in the cnn_serving.py and other functions that use blob storage as their backend. Let me know if you need any further help!
